### ISSUE TITLE
bfsp 404问题，是否更改为@bfchain/pkgm-bfsp包了？

### ISSUE THREAD

**Issue by waterbang** [BioforestChain/developer.bfchain.com#5]
问题如下图：
![image](https://user-images.githubusercontent.com/38105714/158930124-e676fca3-b5e2-4631-b293-7fd27bc00a4b.png)

是否替换为[@bfchain/pkgm-bfsp](https://npmmirror.com/package/@bfchain/pkgm-bfsp)

**Comment by smartwen1** [comment]
您的来信已收到，O(∩_∩)O谢谢,祝您身体健康，工作顺利！

**Comment by kezhaofeng-bnqkl** [comment]
详见pkgm仓库的READMD

**Comment by smartwen1** [comment]
您的来信已收到，O(∩_∩)O谢谢,祝您身体健康，工作顺利！
